name: ETL Pipeline Demo
on:
  push:
    branches:
      - main


jobs:
  extract-data-job:
    runs-on: ubuntu-latest
    steps:
     

      - run: python my_script.py
      - name: checkout code
        uses: actions/checkout@v2
      - name:  run extract.py
        run: python extract.py 
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
         python-version: '3.13' 
   

  transform-data-job:
    runs-on: ubuntu-latest
    needs: extract-data-job
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run transform.py
        run: python transform.py

  load-data-job:
    runs-on: ubuntu-latest
    needs: transform-data-job
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: run load.py
        run: python load.py